name: Build APK

# https://github.com/marketplace/actions/automated-build-android-app-with-github-action

env:
  main_project_module: app
  GRADLE_VERSION: 8.5
  ANDROID_COMPILE_SDK: 34
  ANDROID_BUILD_TOOLS: "34.0.0"
  JAVA_VERSION: 17
  
on:

# push:
#   branches:
#     - 'release/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: true
          # Number of commits to fetch, ootb only 1 commit
          # 0 = all history for all branches and tags. (needed for git describe)
          fetch-depth: 0
          fetch-tags: true
          ref: android

      - name: Set env vars
        run: |
          echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
          echo "${TAG}"

      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-APK
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Decrypt Keystore
        env:
          SIGNING_KEYSTORE_FILE: ${{ secrets.KEYSTORE }}
        run: |
          echo "$SIGNING_KEYSTORE_FILE" | base64 -d > $HOME/release-key.jks

      - name: Build Release APK
        env:
          KEYSTORE: $HOME/release-key.jks
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*.apk
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/release/')
        with:
          tag_name: ${{ github.ref_name }}
          files: MyApp-${{ github.ref_name }}.apk
          generate_release_notes: false
          make_latest: true
          
