name: Build APK

# https://github.com/marketplace/actions/automated-build-android-app-with-github-action

env:
  main_project_module: app
  GRADLE_VERSION: 8.5
  ANDROID_COMPILE_SDK: 34
  ANDROID_BUILD_TOOLS: "34.0.0"
  JAVA_VERSION: 17
  
on:

# push:
#   branches:
#     - 'release/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: true
          # Number of commits to fetch, ootb only 1 commit
          # 0 = all history for all branches and tags. (needed for git describe)
          fetch-depth: 0
          fetch-tags: true
          ref: android

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
          echo "TAG=${{ env.TAG }}"

      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} - APK(s) debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/


      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/release/')
        with:
          tag_name: ${{ github.ref_name }}
          files: MyApp-${{ github.ref_name }}.apk
          generate_release_notes: false
          make_latest: true
          
