name: Build APK

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#secrets-context
# https://github.com/marketplace/actions/automated-build-android-app-with-github-action

env:
  JAVA_VERSION: 17
  APK_PATH_RELEASE: app/build/outputs/apk/release/ananda-marga-fasting-release.apk
  APK_PATH_DEBUG: app/build/outputs/apk/debug/ananda-marga-fasting-debug.apk
  
on:

# push:
#   branches:
#     - 'release/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: true
          # Number of commits to fetch, ootb only 1 commit
          # 0 = all history for all branches and tags. (needed for git describe)
          fetch-depth: 0
          fetch-tags: true
          ref: android

      - name: Set env vars
        run: |
          echo "TAG=${TAG:-$(git describe --tags --abbrev=1 || echo ${{ github.event.repository.name }})}" >> $GITHUB_ENV

      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk debug
        if: false
        run: ./gradlew assembleDebug

      - name: Upload APK Debug - ${{ env.repository_name }}
        if: false
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-debug.apk
          path: ${{ env.APK_PATH_DEBUG }}
          
      - name: DEBUG PRINT GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Get JKS Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: print JKS keystore path
        run: echo "KEYSTORE PATH=${{ steps.decode_keystore.outputs.filePath}}"

      - name: Build Release APK
        env:
          KEYSTORE: ${{ steps.decode_keystore.outputs.filePath}}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.event.repository.name }}-release.apk
          path: ${{ env.APK_PATH_RELEASE }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/release/')
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.APK_PATH_RELEASE }}
          generate_release_notes: false
          make_latest: true
